accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

from .forms import CustomAuthenticationForm, CustomPasswordResetForm, CustomSetPasswordForm

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(form_class=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url = reverse_lazy('accounts:password_reset_done'), form_class=CustomPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class= CustomSetPasswordForm,success_url = reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] 

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', login_required(views.dashboard), name="dashboard"),
    path('search', login_required(views.search), name="search"),

    path('patient/create/', login_required(views.PatientCreateView.as_view()), name='patient-create'),
    path('patient/<int:pk>/update/', login_required(views.PatientUpdateView.as_view()), name='patient-update'),
    path('patient/<int:pk>/delete/', login_required(views.PatientDeleteView.as_view()), name='patient-delete'),
    path('patients/', login_required(views.PatientListView.as_view()), name='patients'),
    path('patient/<int:pk>/', login_required(views.PatientDetailView.as_view()), name='patient-detail'),

    path('chief-complaint/create/', login_required(views.ChiefComplaintCreateView.as_view()), name='chief-complaint-create'),
    path('chief-complaint/create/<int:id>/', login_required(views.patient_chief_complaint_create_view), name='chief-complaint-create-id'),
    path('chief-complaint/<int:pk>/update/', login_required(views.ChiefComplaintUpdateView.as_view()), name='chief-complaint-update'),
    path('chief-complaint/<int:pk>/delete/', login_required(views.ChiefComplaintDeleteView.as_view()), name='chief-complaint-delete'),
    path('chief-complaints/', login_required(views.ChiefComplaintListView.as_view()), name='chief-complaints'),
    path('chief-complaint/<int:pk>/', login_required(views.ChiefComplaintDetailView.as_view()), name='chief-complaint-detail'),

    path('appointment/create/', login_required(views.AppointmentCreateView.as_view()), name='appointment-create'),
    path('appointment/<int:pk>/update/', login_required(views.AppointmentUpdateView.as_view()), name='appointment-update'),
    path('appointment/<int:pk>/delete/', login_required(views.AppointmentDeleteView.as_view()), name='appointment-delete'),
    path('appointments/', login_required(views.AppointmentListView.as_view()), name='appointments'),
    path('appointment/<int:pk>/', login_required(views.AppointmentDetailView.as_view()), name='appointment-detail'),
]

healthdeck/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('kiosk.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kiosk/urls.py
from django.urls import path

from  . import views

app_name = 'kiosk'

urlpatterns = [
    path('', views.index, name="kiosk"),
]

dashboard/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.utils import timezone

from django.utils.translation import gettext_lazy as _

from accounts.models import GENDER_CHOICES

PROVINCE_CHOICES = (
    ('EC', 'Eastern Cape'),
    ('FS', 'Free State'),
    ('GP', 'Gauteng'),
    ('KZN', 'KwaZulu-Natal'),
    ('LP', 'Limpopo'),
    ('MP', 'Mpumalanga'),
    ('NC', 'Northern Cape'),
    ('NW', 'North West'),
    ('WC', 'Western Cape'),
)

class Patient(models.Model):
    first_name = models.CharField(_('first name'), max_length=32)
    middle_name = models.CharField(_('middle name'), max_length=32, blank=True)
    last_name = models.CharField(_('last name'), max_length=32, blank=True)

    phone = models.CharField(_('phone number'), max_length=10, blank=True)    
    email = models.EmailField(_('email address'), blank=True)    

    date_of_birth = models.DateField(_('date of birth'), null=True, blank=True)

    gender = models.CharField(_('gender'), choices=GENDER_CHOICES, max_length=1, blank=True)

    nationality = models.CharField(_('nationality'), max_length=64, blank=True)
    identity_number = models.CharField(_('id or passport'), max_length=13, blank=True)

    address1 = models.CharField(_('address'), max_length=255, blank=True)
    address2 = models.CharField(_('address 2'), max_length=255, blank=True)
    city = models.CharField(_('city'), max_length=255, blank=True)
    zip_code = models.CharField(_('zip'), max_length=10, blank=True)
    province = models.CharField(_('province'), choices=PROVINCE_CHOICES, max_length=3, blank=True)

    def get_absolute_url(self):
        return reverse('dashboard:patient-detail', args=[str(self.id)])

    def __str__(self):
        if self.last_name:
            return '#%s %s %s' % (self.id, self.first_name, self.last_name)
        
        return '#%s %s' % (self.id, self.first_name)


class ChiefComplaint(models.Model):
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE, related_name='complaints')
    date_of_observation = models.DateTimeField(_('date & time of observation'), default=datetime.now)
    complaints = models.TextField(_('complaints'))
    general_condition = models.TextField(_('general condition'), blank=True)
    current_medication = models.TextField(_('current medication'), blank=True)
    allergies = models.TextField(_('allergies'), blank=True)

    blood_pressure = models.CharField(_('blood pressure (mmHg)'), max_length=255, blank=True)
    pulse = models.CharField(_('pulse (b/min)'), max_length=255, blank=True)

    temp = models.CharField(_('temp (°C)'), max_length=255, blank=True)
    weight = models.FloatField(_('weight (KG)'), null=True, blank=True)
    height = models.FloatField(_('height (CM/M)'), null=True, blank=True)
    unirene_dipstick = models.CharField(_('unirene dipstick'), max_length=255, blank=True)

    bmi = models.CharField(_('BMI'), blank=True, max_length=8)
    hiv = models.CharField(_('HIV test'), blank=True, max_length=255)

    immediate_action_taken = models.TextField(_('immediate action taken'), blank=True)
    diagnosis = models.TextField(_('diagnosis'), blank=True)

    def get_absolute_url(self):
        return reverse('dashboard:chief-complaint-detail', args=[str(self.id)])

    def __str__(self):
        return '%s %s %s' % (self.patient, self.date_of_observation, self.complaints)


class Appointment(models.Model):
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE, related_name='appointments')
    date_of_appointment = models.DateTimeField(_('date of appointment'))
    date_appointment_made = models.DateTimeField(_('date appointment made'), default=timezone.now)

    STATUS_CHOICES = (('f', 'Finished'), ('c', 'Cancelled'), ('p', 'Pending'))
    status = models.CharField(_('status'), choices=STATUS_CHOICES, default='p', max_length=1)

    comment = models.TextField(_('comment'))

    class Meta:
        ordering = ['date_of_appointment']

    def get_absolute_url(self):
        return reverse('dashboard:appointment-detail', args=[str(self.id)])

    def __str__(self):
        return '%s | %s | %s' % (self.patient, self.date_of_appointment, self.get_status_display())

dashboard/forms.py
from django import forms
from .models import Patient, ChiefComplaint, Appointment

PATIENT_FIELDS = [
    'first_name',
    'middle_name',
    'last_name',
    'phone',
    'email',
    'date_of_birth',
    'gender',
    'nationality',
    'identity_number',
    'address1',
    'address2',
    'city',
    'zip_code',
    'province',
]

class PatientCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PatientCreationForm, self).__init__(*args, **kwargs)
        self.label_suffix = ""

        # Text fields
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['middle_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control'})
        self.fields['nationality'].widget.attrs.update({'class': 'form-control'})
        self.fields['identity_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['address1'].widget.attrs.update({'class': 'form-control'})
        self.fields['address2'].widget.attrs.update({'class': 'form-control'})
        self.fields['city'].widget.attrs.update({'class': 'form-control'})
        self.fields['zip_code'].widget.attrs.update({'class': 'form-control'})

        # Select fields
        self.fields['gender'].widget.attrs.update({'class': 'form-select', 'rows' : 3})
        self.fields['province'].widget.attrs.update({'class': 'form-select', 'rows' : 3})

    class Meta:
        model = Patient
        fields = PATIENT_FIELDS

CHIEF_COMPLAINT_FIELDS = [
    'patient',
    'date_of_observation',
    'complaints',
    'general_condition',
    'current_medication',
    'allergies',
    'blood_pressure',
    'pulse',
    'temp',
    'weight',
    'height',
    'unirene_dipstick',
    'bmi',
    'hiv',
    'immediate_action_taken',
    'diagnosis',
]

class ChiefComplaintCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ChiefComplaintCreationForm, self).__init__(*args, **kwargs)
        self.label_suffix = ""

        # Select fields
        self.fields['patient'].widget.attrs.update({'class': 'form-select'})

        # Text fields
        self.fields['date_of_observation'].widget.attrs.update({'class': 'form-control'})
        self.fields['complaints'].widget.attrs.update({'class': 'form-control'})
        self.fields['general_condition'].widget.attrs.update({'class': 'form-control'})
        self.fields['current_medication'].widget.attrs.update({'class': 'form-control'})
        self.fields['blood_pressure'].widget.attrs.update({'class': 'form-control'})
        self.fields['pulse'].widget.attrs.update({'class': 'form-control'})
        self.fields['temp'].widget.attrs.update({'class': 'form-control'})
        self.fields['weight'].widget.attrs.update({'class': 'form-control'})
        self.fields['height'].widget.attrs.update({'class': 'form-control'})
        self.fields['unirene_dipstick'].widget.attrs.update({'class': 'form-control'})
        self.fields['bmi'].widget.attrs.update({'class': 'form-control'})
        self.fields['hiv'].widget.attrs.update({'class': 'form-control'})  

        # Textarea fields
        self.fields['complaints'].widget.attrs.update({'class': 'form-control', 'rows' : 3})
        self.fields['general_condition'].widget.attrs.update({'class': 'form-control', 'rows' : 3})
        self.fields['current_medication'].widget.attrs.update({'class': 'form-control', 'rows' : 3})
        self.fields['allergies'].widget.attrs.update({'class': 'form-control', 'rows' : 3})
        self.fields['immediate_action_taken'].widget.attrs.update({'class': 'form-control', 'rows' : 3})
        self.fields['diagnosis'].widget.attrs.update({'class': 'form-control', 'rows' : 3})


    class Meta:
        model = ChiefComplaint
        fields = CHIEF_COMPLAINT_FIELDS



APPOINTMENT_FIELDS = [
    'patient',
    'date_of_appointment',
    'status',
    'comment',
]

class AppointmentCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AppointmentCreationForm, self).__init__(*args, **kwargs)
        self.label_suffix = ""

        self.fields['patient'].widget.attrs.update({'class': 'form-select'})
        self.fields['date_of_appointment'].widget.attrs.update({'class': 'form-control'})
        self.fields['status'].widget.attrs.update({'class': 'form-select'})
        self.fields['comment'].widget.attrs.update({'class': 'form-control', 'rows' : 3})



    class Meta:
        model = Appointment
        fields = APPOINTMENT_FIELDS


class SearchForm(forms.Form):
    term = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))

    

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
import datetime 
from django.utils import timezone
from django.db.models import Q


from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Patient, ChiefComplaint, Appointment

from .forms import SearchForm, ChiefComplaintCreationForm, PatientCreationForm, AppointmentCreationForm, CHIEF_COMPLAINT_FIELDS,PATIENT_FIELDS


def dashboard(request):

    appointments = Appointment.objects.filter(date_of_appointment__gt=timezone.now().date())[:5]

    next_five_days_appointments = []

    for i in range(0, 7):

        today = timezone.now().date()
        start_date = today + datetime.timedelta(days=i)

        appointments_count = Appointment.objects.filter(date_of_appointment__date=start_date, status='p').count()

        next_five_days_appointments.append((start_date, appointments_count))


    return render(request,  'dashboard/dashboard.html', {'appointments': appointments, 'next_five': next_five_days_appointments})



def search(request):

    if request.method == 'POST':
        form = SearchForm(request.POST)

        if form.is_valid():
            term = form.cleaned_data['term']
            #patients = Patient.objects.filter(first_name__icontains=term).filter(last_name__icontains=term)
            patients = Patient.objects.filter(Q(first_name__icontains=term) | Q(last_name__icontains=term) | Q(address1__icontains=term) | Q(city__icontains=term))

            print(patients)
            
        return render(request, 'dashboard/search.html',  {'form': form, 'patients': patients})
    else:
        form = SearchForm()

    return render(request, 'dashboard/search.html', {'form': form})


# View for creating a patient
class PatientCreateView(CreateView):
    model = Patient
    form_class = PatientCreationForm
    success_url = reverse_lazy('dashboard:patients')

# View for updating a patient
class PatientUpdateView(UpdateView):
    model = Patient
    form_class = PatientCreationForm

# View for deleting a patient
class PatientDeleteView(DeleteView):
    model = Patient
    success_url = reverse_lazy('dashboard:patients')

# View for listing all patients
class PatientListView(generic.ListView):
    model = Patient

# View for viewing details of a specific patient
class PatientDetailView(generic.DetailView):
    model = Patient
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['complaints'] = self.object.complaints.all()
        context['appointments'] = self.object.appointments.filter(status='p', date_of_appointment__date__gte=timezone.now().date())

        return context



# View for creating a chief complaint
class ChiefComplaintCreateView(CreateView):
    model = ChiefComplaint
    form_class = ChiefComplaintCreationForm

# View for updating a chief complaint
class ChiefComplaintUpdateView(UpdateView):
    model = ChiefComplaint
    form_class = ChiefComplaintCreationForm

# View for creating a chief complaint
class ChiefComplaintDeleteView(DeleteView):
    model = ChiefComplaint
    success_url = reverse_lazy('dashboard:chief-complaints')

# View for listing all chief complaint
class ChiefComplaintListView(generic.ListView):
    model = ChiefComplaint

# View for viewing details of a specific chief complaint
class ChiefComplaintDetailView(generic.DetailView):
    model = ChiefComplaint


def patient_chief_complaint_create_view(request, id):

    patient = get_object_or_404(Patient, pk=id)    

    if request.method == 'POST':
        form = ChiefComplaintCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('dashboard:patient-detail', pk=id)
            HttpResponseRedirect('/thank-you/')

    else:
        form = ChiefComplaintCreationForm(initial={'patient': patient})

    return render(request, 'dashboard/chiefcomplaint_form.html', {'form': form})





# View for creating a Appointment
class AppointmentCreateView(CreateView):
    model = Appointment
    form_class = AppointmentCreationForm

# View for updating a Appointment
class AppointmentUpdateView(UpdateView):
    model = Appointment
    form_class = AppointmentCreationForm

# View for creating Appointment
class AppointmentDeleteView(DeleteView):
    model = Appointment
    success_url = reverse_lazy('dashboard:appointments')

# View for listing all Appointments
class AppointmentListView(generic.ListView):
    model = Appointment

# View for viewing details of a specific Appointment
class AppointmentDetailView(generic.DetailView):
    model = Appointment






        

dashboard/templates/dashboard/appointment_confirm_delete.html
{% extends "dashboard/base.html" %}

{% block content %}

<h1>Delete Appointment</h1>

<p>Are you sure you want to delete the patient: {{ appointment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Yes, delete">
</form>

{% endblock %}

dashboard/templates/dashboard/chiefcomplaint_confirm_delete.html
{% extends "dashboard/base.html" %}

{% block content %}

<h1>Delete Patient</h1>

<p>Are you sure you want to delete the patient: {{ chiefcomplaint }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

dashboard/templates/dashboard/patient_detail.html
{% extends "dashboard/base.html" %}

{% block content %}    
  <a class="btn btn-success my-1" href="{% url 'dashboard:chief-complaint-create-id'  patient.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
  </svg>
    Add Chief Complaint</a>
  <hr>
  <p><strong>First name:</strong> {{ patient.first_name }}</p>
  <p><strong>Middle name:</strong> {{ patient.middle_name }}</p>
  <p><strong>Last name:</strong> {{ patient.last_name }}</p>
  <p><strong>phone:</strong> {{ patient.phone }}</p>
  <p><strong>Email:</strong> {{ patient.email }}</p>
  <p><strong>Date of Birth:</strong> {{ patient.date_of_birth }}</p>
  <p><strong>Gender:</strong> {{ patient.get_gender_display }}</p>
  <p><strong>Nationality:</strong> {{ patient.nationality }}</p>
  <p><strong>Id or Passport:</strong> {{ patient.identity_number }}</p>
  <p><strong>Address:</strong> {{ patient.address1 }}</p>
  <p><strong>Address 2:</strong> {{ patient.address2 }}</p>
  <p><strong>City:</strong> {{ patient.city }}</p>
  <p><strong>Zip:</strong> {{ patient.zip_code }}</p>
  <p><strong>Province:</strong> {{ patient.get_province_display }}</p>







  <ul class="nav nav-tabs" style="margin-top: 60px;" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="complaintsTab" data-bs-toggle="tab" href="#complaintsListContent" role="tab" aria-controls="home" aria-selected="true">Chief Complaints</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="appointmentsTab" data-bs-toggle="tab" href="#appointmentsListContent" role="tab" aria-controls="profile" aria-selected="false">Appointments</a>
    </li>
  </ul>
  <div class="tab-content" id="tabContent">
    <div class="tab-pane fade show active" id="complaintsListContent" role="tabpanel" aria-labelledby="appointments-tab">
      <h2 class="mt-3">Chief complaints</h2>
      <hr>
      {% if complaints %}
      <div class="table-responsive">
        <table class="table" id='complaintsList'>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">View</th>
              <th scope="col">Update</th>
              <th scope="col">Delete</th>
              <th scope="col">Date of observation</th>
              <th scope="col">Complaints</th>
              <th scope="col">General Condition</th>
              <th scope="col">Current Medication</th>
              <th scope="col">Immediate Action Taken</th>
              <th scope="col">Diagnosis</th>
            </tr>
          </thead>
          
          <tbody>
            {% for complaint in complaints %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td><a href="{% url 'dashboard:chief-complaint-detail' complaint.pk %}" title="View this chief complaint"><i class="fas fa-eye"></i></a></td>
              <td><a href="{% url 'dashboard:chief-complaint-update' complaint.pk %}" title="Update this chief complaint"><i class="fas fa-edit"></i></a></td>
              <td><a href="{% url 'dashboard:chief-complaint-delete' complaint.pk %}" class="text-danger" title="Delete this chief complaint"><i class="fas fa-trash-alt"></i></a></td>
              <td>{{ complaint.date_of_observation|default:"-" }}</td>
              <td>{{ complaint.complaints|default:"-" }}</td>
              <td>{{ complaint.general_condition|default:"-" }}</td>
              <td>{{ complaint.current_medication|default:"-" }}</td>
              <td>{{ complaint.immediate_action_taken|default:"-" }}</td>
              <td>{{ complaint.diagnosis|default:"-" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
        <p>No chief complaints yet</p>
      {% endif %}      
    </div>
    <div class="tab-pane fade" id="appointmentsListContent" role="tabpanel" aria-labelledby="appointments-tab">
      <h2 class="mt-3">Appointments</h2>
      <hr>
      {% if appointments %}
      <div class="table-responsive">
        <table class="table" id='appointmentsList'>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">View</th>
              <th scope="col">Update</th>
              <th scope="col">Delete</th>
              <th scope="col">Date of Appointment</th>
              <th scope="col">Status</th>
              <th scope="col">Comment</th>
            </tr>
          </thead>
          
          <tbody>
            {% for appointment in appointments %}
            <tr>
              <td scope="row">{{ forloop.counter }}</td>
              <td><a href="{% url 'dashboard:appointment-detail' appointment.pk %}" title="View this appointment"><i class="fas fa-eye"></i></a></td>
              <td><a href="{% url 'dashboard:appointment-update' appointment.pk %}" title="Update this appointment"><i class="fas fa-edit"></i></a></td>
              <td><a href="{% url 'dashboard:appointment-delete' appointment.pk %}" class="text-danger" title="Delete this appointment"><i class="fas fa-trash-alt"></i></a></td>
              <td>{{ appointment.date_of_appointment|default:"-" }}</td>
              <td>{{ appointment.get_status_display|default:"-" }}</td>
              <td>{{ appointment.comment|default:"-" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
        <p>No appointments yet</p>
      {% endif %}   

    </div>
  </div>

{% endblock %}

{% block additionalScripts %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#complaintsList').dataTable();
      
      $('#appointmentsList').dataTable();
  } );
  </script>
{% endblock %} 

dashboard/templates/dashboard/patient_list.html
{% extends "dashboard/base.html" %}

{% block content %}
  <h2>Patient List</h2>

    
  <a class="btn btn-success my-1" href="{% url 'dashboard:patient-create' %}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
  </svg>
    Add Patient</a>
  <hr>

  {% if patient_list %}
  <div class="table-responsive">
  <table class="table table-light table-hover table-striped" id="patients_list">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col" colspan="3">Actions</th>
        <th scope="col">First name</th>
        <th scope="col">Middle</th>
        <th scope="col">Last name</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Gender</th>
        <th scope="col">Nationality</th>
        <th scope="col">Identity Number</th>
        <th scope="col">Phone</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patient_list %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td><a href="{% url 'dashboard:patient-detail' patient.pk %}" data-toggle="tooltip" title="View this patient"><i class="fas fa-eye"></i></a></td>
          <td><a href="{% url 'dashboard:patient-update' patient.pk %}" title="Update this patient"><i class="fas fa-edit"></i></a></td>
          <td><a href="{% url 'dashboard:patient-delete' patient.pk %}" class="text-danger" title="Delete this patient"><i class="fas fa-trash-alt"></i></a></td>
          <td>{{ patient.first_name|default:"-" }}</td>
          <td>{{ patient.middle_name|default:"-" }}</td>
          <td>{{ patient.last_name|default:"-" }}</td>
          <td>{{ patient.date_of_birth|default:"-" }}</td>
          <td>{{ patient.get_gender_display|default:"-" }}</td>
          <td>{{ patient.nationality|default:"-" }}</td>
          <td>{{ patient.identity_number|default:"-" }}</td>
          <td>{{ patient.phone|default:"-" }}</td>
          <td>{{ patient.email|default:"-"}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  {% else %}
    <p>There are no patients yet.</p>
  {% endif %} 
{% endblock %}

{% block additionalScripts %}
<script type="text/javascript">
$(document).ready(function() {
    $('#patients_list').dataTable( {
        responsive: true,
    } );
} );
</script>
{% endblock %}